# Suma máxima en una matriz

Este problema consiste en encontrar la suma máxima dentro de una matriz, siguiendo una secuencia determinada.  
La secuencia debe empezar en la esquina superior izquierda y termina en la esquina inferior derecha. Sólo puedes avanzar hacia la derecha o hacia abajo.

$$\begin{bmatrix}
3&7&9&2&7 \\
9&8&3&5&5 \\
1&7&9&8&5 \\
3&8&6&4&10 \\
6&3&9&7&8 \\
\end{bmatrix}$$

Secuencia de la suma máxima:
$$\begin{bmatrix}
(3)&7&9&2&7 \\
(9)&(8)&3&5&5 \\
1&(7)&(9)&(8)&(5) \\
3&8&6&4&(10) \\
6&3&9&7&(8) \\
\end{bmatrix}$$


In [9]:
suma_maxima = 3+9+8+7+9+8+5+10+8
print(suma_maxima)

67


## Programación Dinámica

Este problema se puede plantear como sum(y,x) (Recordemos que para programación, primero se colocaría el índice y, que indica la fila en la que se está trabjando; luego x, que indica la columna).
* Sum representa la secuencia con la suma máxima en el punto (x,y). 
* Cada secuencia siempre empieza con la esquina superior izquierda (0,0).
* La suma máxima en cada punto depende si viene de (y-1,x) o (y,x-1).
* Al llegar a la esquina inferior derecha, sum(n,n) debe tener la mejor respuesta.

La solución recursiva es:  
sum(y,x) = max(sum(y-1,x), sum(y,x-1)) + valor(y,x)
    

In [60]:
def max_sum_in_matrix(matrix):
    #la matriz es de n x n
    n = len(matrix)
    
    # saco una copia de la matriz para almacenar el resultado de sum()
    sum_yx = []
    for y in range(n):
        sum_yx.append(matrix[y].copy())
      
    
    #la primera fila sólo puede venir de (y,x-1), es decir de casiilas de la misma fila
       # la esquina superior debe ser igual
    for x in range(1,n):
        sum_yx[0][x] = sum_yx[0][x-1] + matrix[0][x]
        
    #la primera columna sólo puede venir de (y-1,x), es decir, casillas de la misma columna
    for y in range(1,n):
        sum_yx[y][0] = sum_yx[y-1][0] + matrix[y][0]
        
    # a partir de la segunda fila se puede buscar 
    # tanto en (y,x-1) como en (y-1,x)
    for y in range(1,n):
        for x in range(1,n):
            sum_yx[y][x] = max(sum_yx[y][x-1],sum_yx[y-1][x]) + matrix[y][x]
    
    #retorno la matriz de soluciones sólo para poder analizarla
    return sum_yx[n-1][n-1], sum_yx

    
            
            

In [61]:
matrix = [[3,7,9,2,7],
          [9,8,3,5,5],
         [1,7,9,8,5],
         [3,8,6,4,10],
         [6,3,9,7,8]]

In [62]:
max_sum, sum_matrix = max_sum_in_matrix(matrix)

In [67]:
import numpy as np
sum_matrix = np.matrix(sum_matrix)

Podemos observar que la respuesta se encuentra en la parte inferior derecha. Todas las celdas contienen la suma máxima que se puede obtener.

In [64]:
sum_matrix

matrix([[ 3, 10, 19, 21, 28],
        [12, 20, 23, 28, 33],
        [13, 27, 36, 44, 49],
        [16, 35, 42, 48, 59],
        [22, 38, 51, 58, 67]])

In [68]:
matrix

[[3, 7, 9, 2, 7],
 [9, 8, 3, 5, 5],
 [1, 7, 9, 8, 5],
 [3, 8, 6, 4, 10],
 [6, 3, 9, 7, 8]]

La respuesta: 67, se obtuvo correctamente.

In [69]:
max_sum

67

In [70]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [71]:
max_sum, sum_matrix = max_sum_in_matrix(matrix)

In [73]:
np.matrix(sum_matrix)

matrix([[ 1,  3,  6],
        [ 5, 10, 16],
        [12, 20, 29]])

In [78]:
np.matrix(matrix)

matrix([[10, 10,  3],
        [ 4, 10,  6],
        [ 7, 10, 10]])

Aquí voy a marcar un claro camino ganador.

In [80]:
matrix=[[10,10,3,1],
        [4,10,6,2],
        [7,10,10,3],
        [8,7,10,10]]

In [81]:
max_sum, sum_matrix = max_sum_in_matrix(matrix)

In [82]:
np.matrix(sum_matrix)

matrix([[10, 20, 23, 24],
        [14, 30, 36, 38],
        [21, 40, 50, 53],
        [29, 47, 60, 70]])

In [84]:
np.matrix(matrix)

matrix([[10, 10,  3,  1],
        [ 4, 10,  6,  2],
        [ 7, 10, 10,  3],
        [ 8,  7, 10, 10]])

Cabe señalar que el algoritmo tiene una complejidad de $O(n^2)$ debido al for anidado.

In [85]:
matrix = [[3,7,9,100,7],
          [9,8,3,5,5],
         [1,7,9,8,5],
         [3,8,6,4,10],
         [6,3,9,7,8]]

In [86]:
max_sum, sum_matrix = max_sum_in_matrix(matrix)

In [87]:
np.matrix(sum_matrix)

matrix([[  3,  10,  19, 119, 126],
        [ 12,  20,  23, 124, 131],
        [ 13,  27,  36, 132, 137],
        [ 16,  35,  42, 136, 147],
        [ 22,  38,  51, 143, 155]])

In [88]:
np.matrix(matrix)

matrix([[  3,   7,   9, 100,   7],
        [  9,   8,   3,   5,   5],
        [  1,   7,   9,   8,   5],
        [  3,   8,   6,   4,  10],
        [  6,   3,   9,   7,   8]])

Este último ejemplo lo considero útil, pues empecé a pensar que lo que debía hacer era empezar por la esquina izquierda y elegir el número más grande: 9. Luego, a partir de ahí, elegir. el más grande: 8.  
* 3,9,8,...

Sin embargo, al colocar ese 100, se debe elegir tomar el número más pequeño: 7, para poder llegar al 100, a la respuesta correcta.

$$\begin{bmatrix}
(3)&(7)&(9)&(100)&7 \\
9&8&3&(5)&5 \\
1&7&9&(8)&(5) \\
3&8&6&4&(10) \\
6&3&9&7&(8) \\
\end{bmatrix}$$
