# La subsecuencia más larga $O(n \log{n})$

Esta respuesta está basanda en el artículo de [GeeksforGeeks](https://www.geeksforgeeks.org/longest-monotonically-increasing-subsequence-size-n-log-n/).

Acabo de leer la aplicación y creo que ya puedo resolverlo sin necesidad de ver el código. La respuesta no difiere tanto de mi intento anterior, excepto por un punto fundamental: eliminar listas de la misma longitud.  


Este paso convierte todo en algo mucho más sencillo, de tal forma que las listas están ordenadas de acuerdo a su longitud y a su número final.

Modificaré mi algoritmo anterior un poco, el ordenamiento sigue siendo importante para usar búsqueda binaria. Se ordenará de acuerdo al elemento final. Luego, utilizaré búsqueda binaria para encontrar la lista donde pueda agregar el elemento actual al final. 
* El elemento final de las lista más largas debe ser mayor al elemento final de las listas más cortas.
* Si el elmento actual no es mayor a ningún elemento final, se debe crear un nuevo camino para otra posible solución.

In [44]:
def max_incremental_subarray(array):
    #aquí guardaré los subconjuntos incrementales
    #f(0) siempre será el primer elemento 
    #agrego un número lo bastante grande como para que sea ignorado siempre
    #sirve de límite para el último elemento
    #en una competencia se sabrá el número más grande del array
    #entonces sólo debo establecer un número más grande que el límite
    f_arrays = [[array[0]],[100000000000000000000]]
    
    #voy a recorrer toda la lista para encontrar los subarrays
    for i in range(1,len(array)):
        #en principio, el úncio elemento del subarray es
        #el elemento actual
        subarray = [array[i]]
        #me dirá si empieza una nueva lista
        nuevo = True
              
        ###############################3    
        ##Búsqueda binaria
        ###############################
        a = 0 
        b = len(f_arrays)-1
        l = range(a,b)
        
        while(a<=b):
            centro = (a+b)//2
            x = l[centro] #indice del subarray elegido
            #si el siguiente subarray tiene un número final mayor
            #entonces estoy en el array posible más largo
            if(f_arrays[x][-1]<subarray[0]):
                if(f_arrays[x+1][-1]>subarray[0]):
                    f_arrays.append(f_arrays[x]+subarray)
                    nuevo = False
                    #rompo el while
                    a=b+100
                    #nuevo paso
                    #debo eliminar las listas del mismo tamaño
                    if(len(f_arrays[x+1])==len(f_arrays[-1])):
                        f_arrays.pop(x+1)
                else:
                    a = centro+1
    
            else:
                b = centro-1                
        
        if(nuevo):
            f_arrays.append(subarray)
            #es importante borrar la lista con un elemento
            #si encontramos un elemento más bajo 
            #que pueda generar algo mejor
            if(len(f_arrays[0])==1):
                f_arrays.pop(0)
                
        #Ordeno la lista de acuerdo al número final
        f_arrays = sorted(f_arrays, key=lambda x:x[-1])
        print(f_arrays)
        
        
        
    return f_arrays[-2]

In [36]:
array = [6,2,5,1,7,4,8,3]
print("Array", array)
print("Respuesta", [2,5,7,8])

Array [6, 2, 5, 1, 7, 4, 8, 3]
Respuesta [2, 5, 7, 8]


In [37]:
print("Subarray más largo")
print(max_incremental_subarray(array))
print('#############################')

Subarray más largo
[[2], [100000000000000000000]]
[[2], [2, 5], [100000000000000000000]]
[[1], [2, 5], [100000000000000000000]]
[[1], [2, 5], [2, 5, 7], [100000000000000000000]]
[[1], [1, 4], [2, 5, 7], [100000000000000000000]]
[[1], [1, 4], [2, 5, 7], [2, 5, 7, 8], [100000000000000000000]]
[[1], [1, 3], [2, 5, 7], [2, 5, 7, 8], [100000000000000000000]]
[2, 5, 7, 8]
#############################


Hice muy pocas modificaciones a mi algoritmo anterior. Eso me hace sentir bien, pues parece que no estaba lejos de la respuesta.  
Como dije, el secreto era eliminar las listas de la misma longitud. Ahora voy a explicar por qué:

In [38]:
sublista1 = [1,3]
sublista2 = [1,3,5]

Teniendo ambas listas, imaginemos que ingresa el número 4.  
De acuerdo al algoritmo, buscaríamos una lista donde pueda entrar el 4, es decir, la siguiente lista termina en un número mayor a 4.

In [39]:
sublista1 = [1,3]
sublista2 = [1,3,5] #----> se debe eliminar
sublista3 = [1,3,4]

Ahora ambas listas tienen la misma longitud. Se elimina la que ya existía, ya que, por definición del algoritmo, la nueva lista termina en un elemento menor a la ya existente.

Eliminar las listas de la misma longitud es importante, porque la nueva lista tiene más potencial de ser una lista con más elmentos. Imaginemos que el siguiente elemento es un 5.  
Se puede agregar a dos de las listas.

In [40]:
sublista1 = [1,3,5]
sublista2 = [1,3,5] #----> no se puede agregar
sublista3 = [1,3,4,5]

Entonces, no vale la pena conservar esa lista.

## Comparación de algoritmos

Ahora haré algunas pruebas de validación y luego una de tiempo.

In [45]:
####################
# ALGORITMO O(n2)
####################
def max_incremental_subarray_o2(array):
    #aquí guardaré los subconjuntos incrementales
    #f(0) siempre será el primer elemento 
    f_arrays = [[array[0]]]
    #voy a guardar el índice del subarray más largo
    max_indx = 0
    max_long = 0
    #voy a recorrer toda la lista para encontrar los subarrays
    for i in range(1,len(array)):
        #en principio, el úncio elemento del subarray es
        #el elemento actual
        subarray = [array[i]]
        #voy a buscar en las f(j) inferiores a i
        #si encuentro un elmento final menor
        for j in range(i):
            if(f_arrays[j][-1]<array[i]):
                if(len(subarray)<=len(f_arrays[j])):
                    subarray = f_arrays[j]+[array[i]]
            
        #compruebo si este subconjunto es el de mayor longitud       
        long_sub = len(subarray)
        if(long_sub > max_long):
            max_long = long_sub 
            max_indx = i
        f_arrays.append(subarray)
        
    return f_arrays[max_indx]

In [46]:
################33
#ALGORITMO n LOG(N)
###############
def max_incremental_subarray_log(array):
    #aquí guardaré los subconjuntos incrementales
    #f(0) siempre será el primer elemento 
    #agrego un número lo bastante grande como para que sea ignorado siempre
    #sirve de límite para el último elemento
    #en una competencia se sabrá el número más grande del array
    #entonces sólo debo establecer un número más grande que el límite
    f_arrays = [[array[0]],[100000000000000000000]]
    
    #voy a recorrer toda la lista para encontrar los subarrays
    for i in range(1,len(array)):
        #en principio, el úncio elemento del subarray es
        #el elemento actual
        subarray = [array[i]]
        #me dirá si empieza una nueva lista
        nuevo = True
              
        ###############################3    
        ##Búsqueda binaria
        ###############################
        a = 0 
        b = len(f_arrays)-1
        l = range(a,b)
        
        while(a<=b):
            centro = (a+b)//2
            x = l[centro] #indice del subarray elegido
            #si el siguiente subarray tiene un número final mayor
            #entonces estoy en el array posible más largo
            if(f_arrays[x][-1]<subarray[0]):
                if(f_arrays[x+1][-1]>subarray[0]):
                    f_arrays.append(f_arrays[x]+subarray)
                    nuevo = False
                    #rompo el while
                    a=b+100
                    #nuevo paso
                    #debo eliminar las listas del mismo tamaño
                    if(len(f_arrays[x+1])==len(f_arrays[-1])):
                        f_arrays.pop(x+1)
                else:
                    a = centro+1
    
            else:
                b = centro-1                
        
        if(nuevo):
            f_arrays.append(subarray)
            #es importante borrar la lista con un elemento
            #si encontramos un elemento más bajo 
            #que pueda generar algo mejor
            if(len(f_arrays[0])==1):
                f_arrays.pop(0)
                
        #Ordeno la lista de acuerdo al número final
        f_arrays = sorted(f_arrays, key=lambda x:x[-1])      
        
        
    return f_arrays[-2]

In [55]:
import numpy as np
lista=np.random.randint(1,100,10)
print(lista)

[23 50  7 19 48 23 82  2 47 42]


In [56]:
max_incremental_subarray_o2(lista)

[7, 19, 48, 82]

In [57]:
max_incremental_subarray_log(lista)

[7, 19, 23, 42]

In [59]:
for i in range(10):
    lista=np.random.randint(1,100,10)
    print(lista)
    print(max_incremental_subarray_o2(lista))
    print(max_incremental_subarray_log(lista))
    print()

[88 31 57 72 82 25 63 67 91 81]
[31, 57, 72, 82, 91]
[31, 57, 63, 67, 81]

[27 59 31 85 94 82 15 89 38 15]
[27, 59, 85, 94]
[27, 31, 82, 89]

[53 89  4 19 31 44  1 41 73 65]
[4, 19, 31, 44, 73]
[4, 19, 31, 41, 65]

[12 14 65 74 31  1 37 13  2 10]
[12, 14, 65, 74]
[12, 14, 31, 37]

[56 77 18 33 65 93 90 15  7 54]
[18, 33, 65, 93]
[18, 33, 65, 90]

[78 41 56 15 29  5 49 70 27  8]
[15, 29, 49, 70]
[15, 29, 49, 70]

[27 25 61 98 40 48 86 88 44 31]
[27, 40, 48, 86, 88]
[25, 40, 48, 86, 88]

[87 64 82 10 90 76  5 72 51 19]
[64, 82, 90]
[64, 82, 90]

[35 40 88 83  1  2 61  1  2 45]
[35, 40, 88]
[1, 2, 61]

[34 23 17 30 52 78 49 44 80 54]
[23, 30, 52, 78, 80]
[17, 30, 52, 78, 80]



Es curioso que los algoritmos dan respuestas distintas. El primero se queda con la primera mejor opción que encuentra, el segundo modifica las listas con el potencial de ser mejores.  
Sin embargo, la longitud de ambas listas es la misma, así que los algoritmos funcionan bien.

In [60]:
lista=[1,2,3,4,5,6,7,8,9]
print(max_incremental_subarray_log(lista))
print(max_incremental_subarray_o2(lista))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [61]:
lista=[1,1,1,1,1,1,1,1]
print(max_incremental_subarray_log(lista))
print(max_incremental_subarray_o2(lista))

[1]
[1]


In [67]:
lista = np.arange(1,1001)

In [68]:
len(lista)

1000

In [71]:
print(len(max_incremental_subarray_log(lista)))
print(len(max_incremental_subarray_o2(lista)))

1000
1000


Ahora voy a hacer las pruebas de tiempo

In [73]:
import time

In [76]:
start = time.time()
max_incremental_subarray_log(lista)
end = time.time()
print("Tiempo de ejecución:",end - start)

Tiempo de ejecución: 0.16648483276367188


In [77]:
start = time.time()
max_incremental_subarray_o2(lista)
end = time.time()
print("Tiempo de ejecución:",end - start)

Tiempo de ejecución: 1.4843838214874268


In [102]:
last_num = 1000
for i in range(11):
    print("longitud de la lista")
    print(last_num)
    lista = np.arange(last_num)
    
    start = time.time()
    max_incremental_subarray_log(lista)
    end = time.time()
    print("Tiempo de ejecución nlog(n):",end - start)
    
    start = time.time()
    max_incremental_subarray_o2(lista)
    end = time.time()
    print("Tiempo de ejecución o2",end - start)
    last_num+=100
    
    print()

longitud de la lista
1000
Tiempo de ejecución nlog(n): 0.15059304237365723
Tiempo de ejecución o2 0.9909086227416992

longitud de la lista
1100
Tiempo de ejecución nlog(n): 0.6009197235107422
Tiempo de ejecución o2 1.2363364696502686

longitud de la lista
1200
Tiempo de ejecución nlog(n): 0.13814687728881836
Tiempo de ejecución o2 1.4960925579071045

longitud de la lista
1300
Tiempo de ejecución nlog(n): 0.15554046630859375
Tiempo de ejecución o2 1.8223145008087158

longitud de la lista
1400
Tiempo de ejecución nlog(n): 0.18355059623718262
Tiempo de ejecución o2 2.241605520248413

longitud de la lista
1500
Tiempo de ejecución nlog(n): 0.21793818473815918
Tiempo de ejecución o2 2.647033452987671

longitud de la lista
1600
Tiempo de ejecución nlog(n): 0.2563197612762451
Tiempo de ejecución o2 3.2153220176696777

longitud de la lista
1700
Tiempo de ejecución nlog(n): 0.2612032890319824
Tiempo de ejecución o2 3.737203359603882

longitud de la lista
1800
Tiempo de ejecución nlog(n): 0.28825

Tuve que detener la ejecución porque la complejidad $O(N^2)$ tarda demasiado.

In [104]:
lista = np.arange(1000)
tiempo_nlog = 0
tiempo_o2 = 0

In [108]:
for i in range(10):
    start = time.time()
    max_incremental_subarray_log(lista)
    end = time.time()
    tiempo_nlog += end - start
    
    start = time.time()
    max_incremental_subarray_o2(lista)
    end = time.time()
    tiempo_o2 += end - start

In [109]:
print("Tiempo promedio nlog(n): ",tiempo_nlog/10)

Tiempo promedio nlog(n):  0.21974802017211914


In [110]:
print("Tiempo promedio o2: ",tiempo_o2/10)

Tiempo promedio o2:  1.9354854345321655


El tiempo promedio demuestra la eficiencia del segundo algoritmo. Sobre todo en números más grandes, como se muestra arriba.  
